# SAND with R, chapter3.tex
# 3.3 Graph Layouts 
# Creating network graph - a 5×5×5 lattice
library(sand)
g.l <- make_lattice(c(5, 5, 5))
summary(g.l)

# Creating a network of ‘web-logs’ 
data(aidsblog)
summary(aidsblog)

# Circular layout
igraph_options(vertex.size=3, vertex.label=NA,
               edge.arrow.size=0.5)
par(mfrow=c(1, 2))      #Specifying the graphical parameters - how much graphs are visualized 
plot(g.l, layout=layout_in_circle)
title("5x5x5 Lattice")
plot(aidsblog, layout=layout_in_circle)
title("Blog Network")

# Spring-embedder methods - method of Fruchterman and Reingold
plot(g.l,layout=layout_with_fr)
title("5x5x5 Lattice")
plot(aidsblog,layout=layout_with_fr)
title("Blog Network")

# Energy-placement methods - method of Kamada and Kawai
plot(g.l, layout=layout_with_kk)
title("5x5x5 Lattice")
plot(aidsblog, layout=layout_with_kk)
title("Blog Network")

# Drawing trees
g.tree <- graph_from_literal(1-+2,1-+3,1-+4,2-+5,2-+6,
                             2-+7,3-+8,3-+9,4-+10)
par(mfrow=c(1, 3))
igraph_options(vertex.size=30, edge.arrow.size=0.5,
               vertex.label=NULL)
plot(g.tree, layout=layout_in_circle)
plot(g.tree, layout=layout_as_tree(g.tree, circular=T))
plot(g.tree, layout=layout_as_tree)

# Drawing bipartite graphs 
plot(g.bip, layout= -layout_as_bipartite(g.bip)[,2:1], 
     vertex.size=60, vertex.shape=ifelse(V(g.bip)$type, 
                                         "rectangle", "circle"),
     vertex.label.cex=1.75,
     vertex.color=ifelse(V(g.bip)$type, "red", "cyan"))

# Drawing the graph of the ‘karate club network’ of Zachary
library(igraphdata)
data(karate)

# Reproducible layout
set.seed(42)
l <- layout_with_kk(karate)
l1 <- layout.kamada.kawai(karate)

# Plot undecorated first.
igraph_options(vertex.size=10)
par(mfrow=c(1,1))
plot(karate, layout=l, vertex.label=V(karate), 
     vertex.color=NA)

# Now decorate, starting with labels.
V(karate)$label <- sub("Actor ", "", V(karate)$name)

# Two leaders get shapes different from club members.
V(karate)$shape <- "circle"
V(karate)[c("Mr Hi", "John A")]$shape <- "rectangle"

# Differentiate two factions by color.
V(karate)[Faction == 1]$color <- "red"
V(karate)[Faction == 2]$color <- "dodgerblue"

# Vertex area proportional to vertex strength
# (i.e., total weight of incident edges).
V(karate)$size <- 4*sqrt(strength(karate))
V(karate)$size2 <- V(karate)$size * .5

# Weight edges by number of common activities
E(karate)$width <- E(karate)$weight

# Color edges by within/between faction.
F1 <- V(karate)[Faction==1]
F2 <- V(karate)[Faction==2]
E(karate)[ F1 %--% F1 ]$color <- "pink"
E(karate)[ F2 %--% F2 ]$color <- "lightblue"
E(karate)[ F1 %--% F2 ]$color <- "yellow"

# Offset vertex labels for smaller points (default=0).
V(karate)$label.dist <- 
  ifelse(V(karate)$size >= 9.0, 0, 1.0)

# Plot decorated graph, using same layout.
plot(karate, layout=l)

# Drawing the Lazega lawyer network supplying the graphical
# parameters to the plotting command
library(sand)
data(lazega)

# Office location indicated by color.
colbar <- c("red", "dodgerblue", "goldenrod")
v.colors <- colbar[V(lazega)$Office]

# Type of practice indicated by vertex shape.
v.shapes <- c("circle", "square")[V(lazega)$Practice]

# Vertex size proportional to years with firm.
v.size <- 3.5*sqrt(V(lazega)$Years)

# Label vertices according to seniority.
v.label <- V(lazega)$Seniority

# Reproducible layout.
set.seed(42)
l <- layout_with_fr(lazega)
plot(lazega, layout=l, vertex.color=v.colors,
     vertex.shape=v.shapes, vertex.size=v.size,
     vertex.label=v.label)S

# Visualization of a subnetwork of French political blogs
# Loading and exploring data
library(sand)
summary(fblog)
party.names <- sort(unique(V(fblog)$PolParty))   #political parties as vertices
party.names

# Creating te network-graph using layouts generated by the Kamada–Kawai algorithm
set.seed(42)
l = layout_with_kk(fblog)
party.nums.f <- as.factor(V(fblog)$PolParty)
party.nums <- as.numeric(party.nums.f)

# igraph color palette has 8 colors
# 9 colors needed (for 9 political parties)
library(RColorBrewer)
colrs <- brewer.pal(9,"Set1")
V(fblog)$color <- colrs[party.nums]
plot(fblog, layout=l, vertex.label=NA,
     vertex.size=3)

# Creating te network-graph using layouts generated by the DrL algorithm
set.seed(42)
l <- layout_with_drl(fblog)
plot(fblog, layout=l, vertex.size=5, vertex.label=NA)

# Coarsen a network graph prior to visualization, replacing groups of vertices 
# with single meta-vertices using French political blog data
# Aggregating edges between groups
fblog.c <- contract(fblog, party.nums)
E(fblog.c)$weight <- 1
fblog.c <- simplify(fblog.c)

# Ploting
party.size <- as.vector(table(V(fblog)$PolParty))
plot(fblog.c, vertex.size=5*sqrt(party.size),
     vertex.label=party.names, vertex.color=colrs,
     edge.width=sqrt(E(fblog.c)$weight),
     vertex.label.dist=3.5, edge.arrow.size=0)

# Showing a subgraph
# Extracting the (1 order) neighborhoods surrounding each vertex
data(karate)
k.nbhds <- make_ego_graph(karate, order=1)

# Retrieving information of subnetworks
sapply(k.nbhds, vcount)

# Plotting the two largest subnetworks
k.1 <- k.nbhds[[1]]
k.34 <- k.nbhds[[34]]
par(mfrow=c(1,2))
plot(k.1, vertex.label=NA,
     vertex.color=c("red", rep("lightblue", 16)))
plot(k.34, vertex.label=NA,
     vertex.color=c(rep("lightblue", 17), "red"))
